import { useQuery } from "@apollo/client";
import Head from "next/head";
import { Fragment, useMemo } from "react";
import { Tooltip } from "react-tooltip";

import Age from "../components/sections/Age";
import Chronic from "../components/sections/Chronic";
import Footer from "../components/sections/Footer";
import Hero from "../components/sections/Hero";
import Locations from "../components/sections/Locations";
import Race from "../components/sections/Race";
import Summary from "../components/sections/Summary";
import Trends from "../components/sections/Trends";
import { CriteriaState } from "../graphql/Infograph";

import { GET_CRITERIA, GET_SUMMARY } from "../graphql/Query";

function Home() {
  const { data: criteriaState } = useQuery<{ criteria: CriteriaState }>(
    GET_CRITERIA,
  );
  const criteria = criteriaState?.criteria;
  const { data } = useQuery(GET_SUMMARY, {
    variables: {
      year: criteria?.year,
      state: criteria?.state,
      disease: criteria?.disease,
      age: criteria?.variant === "AGE" ? criteria?.param : "",
      sex: criteria?.variant === "SEX" ? criteria?.param : "",
      race: criteria?.variant === "RACE" ? criteria?.param : "",
    },
  });

  return (
    <Fragment>
      <Head>
        <title>Blending 101 - Infographic</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <a id="props-basic"> ◕‿‿◕ </a>

        <Tooltip anchorId="props-basic" content="hello world!" />
        <Hero />
        <Summary {...criteriaState?.criteria!} />
        <Trends {...criteriaState?.criteria!} />
        <section id="Chronic-Diseases">
          <div className="container-fluid w-90">
            <Chronic
              active={criteriaState?.criteria.disease || ""}
              diseases={data?.showInfoData?.diseases || []}
            />
            <Race
              active={criteriaState?.criteria.param || ""}
              races={data?.showInfoData?.race || []}
              sex={data?.showInfoData?.sex || []}
            />
            <Age
              active={criteriaState?.criteria.param || ""}
              ages={data?.showInfoData?.age || []}
            />
          </div>
        </section>
        <Locations {...criteriaState?.criteria!} />
      </main>
      <Footer />
    </Fragment>
  );
}

export default Home;
