import { useQuery } from "@apollo/client";
import Head from "next/head";
import { Fragment, useMemo } from "react";
import { Tooltip } from "react-tooltip";

import Age from "../components/sections/Age";
import Chronic from "../components/sections/Chronic";
import Footer from "../components/sections/Footer";
import Hero from "../components/sections/Hero";
import Locations from "../components/sections/Locations";
import Race from "../components/sections/Race";
import Summary from "../components/sections/Summary";
import Trends from "../components/sections/Trends";
import { CriteriaState } from "../graphql/Infograph";

import { GET_CRITERIA, GET_SUMMARY } from "../graphql/Incidence";
import { useCriteria, useDataset } from "../components/context/VariantProvider";

function Home() {
  const dataSet = useDataset();
  const criteria = useCriteria();
  const { data } = useQuery(GET_SUMMARY, {
    variables: {
      year: criteria?.year,
      state: criteria?.state,
      disease: criteria?.disease,
      age: criteria?.age,
      sex: criteria?.sex,
      race: criteria?.race,
      dataSet,
    },
  });

  return (
    <Fragment>
      <Head>
        <title>Blending 101 - Infographic</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero />
        <Summary {...criteria!} />
        <Trends {...criteria!} />
        <section id="Chronic-Diseases">
          <div className="container-fluid w-90">
            <Chronic
              active={criteria?.disease || ""}
              diseases={data?.showInfoData?.diseases || []}
            />
            <Race
              active={criteria?.race || ""}
              races={data?.showInfoData?.race || []}
              sex={data?.showInfoData?.sex || []}
            />
            <Age
              active={criteria?.age || ""}
              ages={data?.showInfoData?.age || []}
            />
          </div>
        </section>
        <Locations {...criteria!} />
      </main>
      <Footer />
    </Fragment>
  );
}

export default Home;
