import Head from "next/head";
import { Fragment } from "react";
import Footer from "../components/sections/Footer";
import Hero from "../components/sections/Hero";
import Summary from "../components/sections/Summary";

export default function Home() {
  return (
    <Fragment>
      <Head>
        <title>Blending 101 - Infographic</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero />
        <Summary />
      </main>
      <Footer />
    </Fragment>
  );
}
